name: My workflow # Name of the workflow
on: push # Events that trigger the jobs

jobs: # List of tasks
  job-1: # id of the job
    name: Job 1 # Name of the job
    runs-on: ubuntu-latest # SO of the server
    steps: # List of subtasks
      - name: Subtask 1-1 # Name of the subtask
        run: echo "Soy una github Action y estoy funcionando" # Command to execute
